In [9]:
import pandas as pd
import numpy as np

In [10]:
#load sataset
from sklearn .datasets import load_breast_cancer
data = load_breast_cancer()
# from sklern import datasets
# datasets.load_breast_cancer()

In [11]:
data.target_names

array(['malignant', 'benign'], dtype='<U9')

In [12]:
df=pd.DataFrame(np.c_[data.data,data.target],columns=[list(data.feature_names)+['target']])
df

mean radius mean texture mean perimeter mean area mean smoothness  \
0         17.99        10.38         122.80    1001.0         0.11840   
1         20.57        17.77         132.90    1326.0         0.08474   
2         19.69        21.25         130.00    1203.0         0.10960   
3         11.42        20.38          77.58     386.1         0.14250   
4         20.29        14.34         135.10    1297.0         0.10030   
..          ...          ...            ...       ...             ...   
564       21.56        22.39         142.00    1479.0         0.11100   
565       20.13        28.25         131.20    1261.0         0.09780   
566       16.60        28.08         108.30     858.1         0.08455   
567       20.60        29.33         140.10    1265.0         0.11780   
568        7.76        24.54          47.92     181.0         0.05263   

    mean compactness mean concavity mean concave points mean symmetry  \
0            0.27760        0.30010             0.14710        0.2419   
1            0.07864        0.08690             0.07017        0.1812   
2            0.15990        0.19740             0.12790        0.2069   
3            0.28390        0.24140             0.10520        0.2597   
4            0.13280        0.19800             0.10430        0.1809   
..               ...            ...                 ...           ...   
564          0.11590        0.24390             0.13890        0.1726   
565          0.10340        0.14400             0.09791        0.1752   
566          0.10230        0.09251             0.05302        0.1590   
567          0.27700        0.35140             0.15200        0.2397   
568          0.04362        0.00000             0.00000        0.1587   

    mean fractal dimension  ... worst texture worst perimeter worst area  \
0                  0.07871  ...         17.33          184.60     2019.0   
1                  0.05667  ...         23.41          158.80     1956.0   
2                  0.05999  ...         25.53          152.50     1709.0   
3                  0.09744  ...         26.50           98.87      567.7   
4                  0.05883  ...         16.67          152.20     1575.0   
..                     ...  ...           ...             ...        ...   
564                0.05623  ...         26.40          166.10     2027.0   
565                0.05533  ...         38.25          155.00     1731.0   
566                0.05648  ...         34.12          126.70     1124.0   
567                0.07016  ...         39.42          184.60     1821.0   
568                0.05884  ...         30.37           59.16      268.6   

    worst smoothness worst compactness worst concavity worst concave points  \
0            0.16220           0.66560          0.7119               0.2654   
1            0.12380           0.18660          0.2416               0.1860   
2            0.14440           0.42450          0.4504               0.2430   
3            0.20980           0.86630          0.6869               0.2575   
4            0.13740           0.20500          0.4000               0.1625   
..               ...               ...             ...                  ...   
564          0.14100           0.21130          0.4107               0.2216   
565          0.11660           0.19220          0.3215               0.1628   
566          0.11390           0.30940          0.3403               0.1418   
567          0.16500           0.86810          0.9387               0.2650   
568          0.08996           0.06444          0.0000               0.0000   

    worst symmetry worst fractal dimension target  
0           0.4601                 0.11890    0.0  
1           0.2750                 0.08902    0.0  
2           0.3613                 0.08758    0.0  
3           0.6638                 0.17300    0.0  
4           0.2364                 0.07678    0.0  
..             ...                     ...    ...  
564         0.2060      

In [13]:
x=df.iloc[:,0:-1]
y=df.iloc[:,-1]
from sklearn.tree import DecisionTreeClassifier
DecisionTreeClassifier().fit(x,y)

C:\Users\gunapati vaishnavi\anaconda3\lib\site-packages\sklearn\utils\validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['tuple']. An error will be raised in 1.2.
  warnings.warn(


DecisionTreeClassifier()

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size = 0.8)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(455, 30)
(114, 30)
(455,)
(114,)


In [15]:
from sklearn.tree import DecisionTreeClassifier

clf=DecisionTreeClassifier(criterion='gini')

In [16]:
clf.fit(x_train,y_train)

C:\Users\gunapati vaishnavi\anaconda3\lib\site-packages\sklearn\utils\validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['tuple']. An error will be raised in 1.2.
  warnings.warn(


DecisionTreeClassifier()

In [17]:
clf.score(x_test,y_test)

C:\Users\gunapati vaishnavi\anaconda3\lib\site-packages\sklearn\utils\validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['tuple']. An error will be raised in 1.2.
  warnings.warn(


0.9473684210526315

In [18]:
# knn


x=df.iloc[:,0:-1]
y=df.iloc[:,-1]
from sklearn.neighbors import KNeighborsClassifier
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=0)

In [19]:
knn= KNeighborsClassifier()
knn.fit(x_train,y_train)

C:\Users\gunapati vaishnavi\anaconda3\lib\site-packages\sklearn\utils\validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['tuple']. An error will be raised in 1.2.
  warnings.warn(


KNeighborsClassifier()

In [20]:
y_pred=knn.predict(x_test)

C:\Users\gunapati vaishnavi\anaconda3\lib\site-packages\sklearn\utils\validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['tuple']. An error will be raised in 1.2.
  warnings.warn(


In [30]:
from sklearn .metrics import confusion_matrix,accuracy_score

In [32]:
confusion_matrix(y_test,y_pred)

array([[59,  4],
       [11, 97]], dtype=int64)

In [34]:
# random forest

from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(x_train,y_train)

C:\Users\gunapati vaishnavi\anaconda3\lib\site-packages\sklearn\utils\validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['tuple']. An error will be raised in 1.2.
  warnings.warn(


RandomForestClassifier()

In [36]:
rf.predict(x_test)

C:\Users\gunapati vaishnavi\anaconda3\lib\site-packages\sklearn\utils\validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['tuple']. An error will be raised in 1.2.
  warnings.warn(


array([0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1.,
       0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 1., 0., 1., 1., 1., 0., 0.,
       0., 0., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 0., 1., 0., 0.,
       0., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 0., 0., 0., 1., 0.,
       1., 1., 1., 0., 0., 1., 0., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1.,
       1., 0., 0., 1., 1., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 1.,
       1., 1., 0., 1., 0., 1., 0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1.,
       1.])

In [38]:
confusion_matrix(y_test,y_pred)

array([[59,  4],
       [11, 97]], dtype=int64)

In [39]:
accuracy_score(y_test,y_pred)

0.9122807017543859

In [ ]:
x=df.iloc[:,0:-1]
y=df.iloc[:,-1]